name: vidyamani
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  logger: ^2.0.2+1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.13.6
  random_string: ^2.3.1
  email_validator: ^2.1.17
  flutter_local_notifications: ^16.2.0
  flutter_zoom_drawer: ^3.1.1
  shared_preferences: ^2.2.2
  get: ^4.6.6
  carousel_slider: ^4.2.1

flutter:
  assets:
   - lib/assets/images/logo.jpg
  uses-material-design: true
