name: vidyamani
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  circular_countdown_timer: ^0.2.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  logger: ^2.0.2+1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.13.6
  random_string: ^2.3.1
  email_validator: ^2.1.17
  flutter_local_notifications: ^16.2.0
  flutter_zoom_drawer: ^3.1.1
  shared_preferences: ^2.2.2
  get: ^4.6.6
  carousel_slider: ^4.2.1
  firebase_analytics_web: ^0.5.5+11
  video_player: ^2.8.1
  fullscreen_window: ^1.0.3
  app_popup_menu: ^1.0.0
  agora_rtc_engine: ^6.1.1
  iris_method_channel: ^2.0.0-dev.4
 
  agora_rtm: 
  intl: ^0.19.0
  http: ^1.1.2
  url_launcher: ^6.0.13
  permission_handler: ^11.1.0
  image_picker: ^1.0.6
  ffi: ^2.1.0
  meta: ^1.10.0
  json_annotation: ^4.8.1
  async: ^2.11.0
  chewie: ^1.7.4
  expandable_text: ^2.3.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  geocoding: 
  geolocator:


dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/logowhite.png
    - lib/assets/images/google.png
    - lib/assets/images/skillbasedcourses.png
    - lib/assets/images/featuredcourses.png
    - lib/assets/videos/cat.mp4
    - lib/assets/videos/sigma.mp4
    - lib/assets/images/placeholder_image.png
    - lib/assets/images/shorts.png
    - lib/assets/images/skillBasedCourse.png
    - lib/assets/images/audioBooks.png
    - lib/assets/images/humanRights.png
    - lib/assets/images/classBasedCourse.png

  uses-material-design: true
