name: vidyamani
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  circular_countdown_timer: 
  firebase_core: 
  firebase_auth: 
  firebase_messaging:
  firebase_storage:
  firebase_analytics: 
  logger: 
  animated_splash_screen: 
  page_transition: 
  google_sign_in: 
  cloud_firestore: 
  random_string: 
  email_validator: 
  flutter_local_notifications: 
  shared_preferences: 
  get: 
  carousel_slider: 
  firebase_analytics_web: 
  video_player: 
  google_mobile_ads: 
  intl: 
  http: 
  url_launcher: 
  permission_handler: 
  image_picker: 
  ffi: 
  meta: 
  json_annotation: 
  async: 
  chewie:
  expandable_text:
  flutter_rating_bar: 
  flutter_riverpod:
  flutter_hooks: 
  hooks_riverpod: 
  geocoding: 
  geolocator:
  lottie:
  sign_in_with_apple: 
  crypto: 
  phonepe_payment_sdk:
  


dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/logowhite.png
    - lib/assets/images/google.png
    - lib/assets/images/skillbasedcourses.png
    - lib/assets/images/featuredcourses.png
    - lib/assets/videos/cat.mp4
    - lib/assets/videos/sigma.mp4
    - lib/assets/images/placeholder_image.png
    - lib/assets/images/shorts.png
    - lib/assets/images/skillBasedCourse.png
    - lib/assets/images/audioBooks.png
    - lib/assets/images/humanRights.png
    - lib/assets/images/classBasedCourse.png
    - lib/assets/lottie/coin_animation.json
    - lib/assets/images/logohalf.png

  uses-material-design: true
